name = "OpenEEW"
uuid = "37fef7b0-badb-4543-bf24-33993a788fd1"
authors = ["Tim Clements <thclements@g.harvard.edu> and contributors"]
version = "0.1.0"

[deps]
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"

[compat]
LazyJSON = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
